### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by alanshaw**

### CODE REVIEW

**Comment by mikeal** [comment]
happy to merge this, but we should probably deprecate this library at some point because it doesn’t match either the new or old IPLD interfaces.

**Comment by alanshaw** [comment]
It’s just that its used by dag-cbor-links which is the real problem I want fixed just now: https://github.com/mikeal/dag-cbor-links/pull/55

**Comment by alanshaw** [comment]
Please can has release 🙏

**Comment by mikeal** [comment]
Ah, ok, that makes sense. That links API is part of the new codec interface so once js-ipfs moves to that (sometime in the future, no idea when though) this will naturally get deprecated.

Published 0.6.2

**Comment by alanshaw** [comment]
Thank you :) https://github.com/mikeal/dag-cbor-links/pull/55 is now ready for review.

**Pull request merged**
